export const tenantApiActions = [
  {
    group: "Tenant lifecycle",
    action: "List, inspect, and register tenants",
    method: "GET/POST",
    path: "/platform/api/v1/tenants",
    ui: "Overview, tenants list, and onboarding wizard",
  },
  {
    group: "Tenant lifecycle",
    action: "Read tenant details",
    method: "GET",
    path: "/platform/api/v1/tenants/{tenantId}",
    ui: "Tenant details header and configuration tab",
  },
  {
    group: "Tenant lifecycle",
    action: "Activate tenant",
    method: "POST",
    path: "/platform/api/v1/tenants/{tenantId}/activate",
    ui: "Tenant details actions",
  },
  {
    group: "Tenant lifecycle",
    action: "Suspend tenant",
    method: "POST",
    path: "/platform/api/v1/tenants/{tenantId}/suspend",
    ui: "Sensitive lifecycle action",
  },
  {
    group: "Tenant lifecycle",
    action: "Archive tenant",
    method: "POST",
    path: "/platform/api/v1/tenants/{tenantId}/archive",
    ui: "Sensitive lifecycle action",
  },
  {
    group: "Placement",
    action: "Read placement",
    method: "GET",
    path: "/platform/api/v1/tenants/{tenantId}/placement",
    ui: "Tenant details placement tab",
  },
  {
    group: "Identity",
    action: "List, inspect, and create tenant members",
    method: "GET/POST",
    path: "/platform/api/v1/tenants/{tenantId}/members",
    ui: "Invite owner/admin form",
  },
  {
    group: "Identity",
    action: "Activate, suspend, remove members",
    method: "POST",
    path: "/platform/api/v1/tenants/{tenantId}/members/{userId}/{action}",
    ui: "Member row actions",
  },
  {
    group: "Identity",
    action: "Assign and revoke tenant roles",
    method: "POST/DELETE",
    path: "/platform/api/v1/tenants/{tenantId}/members/{userId}/roles",
    ui: "Sensitive role actions",
  },
  {
    group: "Auth config",
    action: "Read effective, validate, or preview auth policy",
    method: "GET/POST",
    path: "/platform/api/v1/tenants/{tenantId}/auth-config/{effective|validate|preview}",
    ui: "Onboarding review and auth tab",
  },
  {
    group: "Auth config",
    action: "Update full auth config",
    method: "PUT",
    path: "/platform/api/v1/tenants/{tenantId}/auth-config",
    ui: "Onboarding and auth tab",
  },
  {
    group: "Auth config",
    action: "Patch MFA/session, list versions, and rollback",
    method: "GET/PATCH/POST",
    path: "/platform/api/v1/tenants/{tenantId}/auth-config/{mfa-policy|session-policy|versions|rollback}",
    ui: "Tenant details auth tab",
  },
  {
    group: "Federation",
    action: "Upsert, delete, setup, and preview provider mappings",
    method: "PUT/DELETE/GET/POST",
    path: "/platform/api/v1/tenants/{tenantId}/auth-config/federated-providers/{providerKey}",
    ui: "Federation setup section",
  },
  {
    group: "Context",
    action: "Read, assign, and unassign market or organization context",
    method: "GET/PUT/DELETE",
    path: "/platform/api/v1/tenants/{tenantId}/{market-context|organization-context|markets|organizations}",
    ui: "Markets and organizations tabs",
  },
  {
    group: "Policies",
    action: "Upsert, transition, clone, expire, resolve, and explain bindings",
    method: "PUT/PATCH/POST/DELETE",
    path: "/platform/api/v1/policies/{policyKey}/bindings",
    ui: "Policies page and tenant policies tab",
  },
  {
    group: "Policies",
    action: "Create, validate, activate, list, and deprecate definitions",
    method: "GET/POST",
    path: "/platform/api/v1/policies/definitions",
    ui: "Policies page definition controls",
  },
  {
    group: "Policies",
    action: "Inspect and invalidate policy caches",
    method: "GET/DELETE",
    path: "/platform/api/v1/policies/_cache",
    ui: "Policies page operator section",
  },
] as const;
