import type { Locale } from "@repo/i18n";
import { getMessages } from "@repo/i18n";
import { getSession } from "@repo/auth";
import {
  AppShell,
  Breadcrumb,
  Button,
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
  EmptyState,
  PageHeader,
} from "@repo/ui";
import { PermissionGate } from "@repo/ui/permission-gate";
import { createTranslator } from "next-intl";
import { starterMetrics } from "@/mock-data";

function getNavItems(locale: string) {
  return [
    {
      label: "Docs",
      href: "/" + locale + "/docs",
      permission: "docs:read",
    },
  ];
}

export default async function DocsPage({
  params,
}: {
  params: Promise<{ locale: Locale }>;
}) {
  const { locale } = await params;
  const messages = await getMessages(locale);
  const t = createTranslator({ locale, messages });
  const session = await getSession();

  return (
    <AppShell
      appName="Docs"
      navItems={getNavItems(locale)}
      user={session.user}
      tenant={session.currentTenant}
      tenants={session.availableTenants}
      locale={locale}
      session={session}
      logoutUrl={`/api/auth/logout?locale=${locale}`}
      breadcrumb={
        <Breadcrumb
          items={[{ label: "Juris", href: "/" + locale }, { label: "Docs" }]}
        />
      }
    >
      <PermissionGate
        session={session}`}
        permission="docs:read"
        fallback={
          <EmptyState
            title="Access denied"
            description="Your mock session does not include this permission."
          />
        }
      >
        <PageHeader
          title="Docs"
          description="Enterprise-ready workspace generated by the Juris bootstrap CLI."
          actions={<Button variant="outline">{t("common.search")}</Button>}
        />
        <div className="grid gap-4 lg:grid-cols-3">
          {starterMetrics.map((metric) => (
            <Card key={metric.title}>
              <CardHeader>
                <CardTitle>{metric.title}</CardTitle>
                <CardDescription>{metric.description}</CardDescription>
              </CardHeader>
              <CardContent className="text-2xl font-semibold">
                {metric.value}
              </CardContent>
            </Card>
          ))}
        </div>
      </PermissionGate>
    </AppShell>
  );
}
